name: CI

on:
  # Specify the event that will trigger the workflow
  pull_request:
    branches: [ "main" ]

env:
  # Set the value of global environment variable
  GLOBAL_VARIABLE: global_value

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Set the value of local environment variable
      JOB_VARIABLE: job_value

    steps:
      # Use checkout action to check out the repository on the runner
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Python to 3.9 using setup-python action
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: print secret
        run: | 
          echo "my secret is ${{secrets.supersecret}}"  

      # Run the hello_world.py python script
      - name: Run Python script
        run: |
          python3 hello_world.py

      - name: Print Variables
        # Write the environment variable whose value is set
        run: |
          echo "Global Variable: ${{ env.GLOBAL_VARIABLE }}"
          echo "Set job Variable: ${{ env.JOB_VARIABLE }}"
